Changes to deprecate powervs-provider-id-fmt flat
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1032
Opened 2023-01-16 03:22 UTC by Karthik-K-N

**What this PR does / why we need it**:

Currently for Power VS clusters provider id format is set via powervs-provider-id-fmt flag, With recent merge of VPC CCM support [PR](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1015) we have introduced flag `provider-id-fmt`, same can be used to set provider id format for Power VS as well.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1024

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2023-01-16 06:53 UTC, mkumatag requested changes

2023-01-16 06:53 UTC, mkumatag commented on docs/proposal/20230113-capibm-cli-tool.md
> +# CLI tool for Cluster API Provider IBM Cloud
Why this doc included in this PR?

2023-01-16 06:53 UTC, mkumatag commented on main.go
>  	)
Lets add following code to deprecate it
```golang
	fs.MarkDeprecated("powervs-provider-id-fmt", "please use provider-id-fmt flag")
```

2023-01-16 06:53 UTC, mkumatag commented on main.go
> +		setupLog.Info("Power VS ProviderID format is set to v1 version, Note: its deprecated use provider-id-fmt to provider id format")
with the above `MarkDeprecated` call, you may not need this explicit message anymore

2023-01-17 04:58 UTC, Karthik-K-N commented on docs/proposal/20230113-capibm-cli-tool.md
> +# CLI tool for Cluster API Provider IBM Cloud
By mistake removed it.

2023-01-17 04:59 UTC, Karthik-K-N commented on main.go
>  	)
Updated it accordingly.

2023-01-17 05:23 UTC, mkumatag approved these changes
/lgtm

2023-01-17 05:24 UTC, merged