Add initial code for powervs network list
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1075
Opened 2023-02-06 11:14 UTC by yussufsh

**What this PR does / why we need it**:

Add support for listing PowerVS network.
Client code for authentication and printing results.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2023-02-06 11:15 UTC, yussufsh commented
/cc @mkumatag @Karthik-K-N @Prajyot-Parab @dharaneeshvrd

2023-02-06 11:17 UTC, yussufsh commented
I have taken `utils.go` code from open PR #1071

2023-02-07 13:09 UTC, Prajyot-Parab commented
/ok-to-test

2023-02-07 14:14 UTC, Prajyot-Parab commented on cmd/capibmadm/options/options.go
> +	cmd.Flags().StringVarP(&GlobalOptions.Output, "output", "o", "table", "The output format of the results. Possible values: table,json,yaml")
I dont see yaml support so this can be removed.

2023-02-07 14:56 UTC, Prajyot-Parab requested changes

2023-02-07 14:56 UTC, Prajyot-Parab commented on cmd/capibmadm/cmd/powervs/network/list.go
> +			DhcpManaged: *network.Jumbo,
This should be `network.Jumbo` -> `network.DhcpManaged`

2023-02-07 14:57 UTC, Prajyot-Parab commented
```
prajyotparab@Prajyots-MacBook-Pro capibmadm % ./capibmadm powervs network list --service-instance-id d53da3bf-1f4a-42fa-9735-acf16b1a05cd --zone osa21 -o json
Listing PowerVS networks service-instance-id="d53da3bf-1f4a-42fa-9735-acf16b1a05cd" zone="osa21"
{
  "items": [
    {
      "id": "b0271ffe-16e3-4cdb-a3c6-3ea37832d6a5",
      "name": "capi-net-p2p",
      "type": "pub-vlan",
      "vlanID": 2024,
      "jumbo": false
    }
  ]
}%       
```
@yussufsh `DhcpManaged` should be part of items list? or above o/p is as expected?

2023-02-07 15:08 UTC, yussufsh commented
> @yussufsh `DhcpManaged` should be part of items list? or above o/p is as expected?

I have fixed this one, initially I thought it would handle nil value as well, but it is removed from json data when the value is `false`.

2023-02-07 16:31 UTC, Prajyot-Parab commented
```
prajyotparab@Prajyots-MacBook-Pro capibmadm % ./capibmadm powervs network list --service-instance-id d53da3bf-1f4a-42fa-9735-acf16b1a05cd --zone osa21 -o jso
n
Listing PowerVS networks service-instance-id="d53da3bf-1f4a-42fa-9735-acf16b1a05cd" zone="osa21"
{
  "items": [
    {
      "id": "dd7dd087-45ee-4147-bf8b-fb88c4130e0e",
      "name": "capi-net-p2p",
      "type": "pub-vlan",
      "vlanID": 2024,
      "jumbo": false,
      "dhcpManaged": false
    }
  ]
}%                                                                                                                                                           

prajyotparab@Prajyots-MacBook-Pro capibmadm % ./capibmadm powervs network list --service-instance-id d53da3bf-1f4a-42fa-9735-acf16b1a05cd --zone osa21      
Listing PowerVS networks service-instance-id="d53da3bf-1f4a-42fa-9735-acf16b1a05cd" zone="osa21"
NETWORK ID                             NAME           TYPE       VLAN ID   JUMBO   DHCP MANAGED
dd7dd087-45ee-4147-bf8b-fb88c4130e0e   capi-net-p2p   pub-vlan   2024      false   false
```

/lgtm

2023-02-08 02:47 UTC, mkumatag commented
Lets wait for #1081 to merge!

2023-02-08 07:09 UTC, yussufsh commented
> Lets wait for #1081 to merge!

@mkumatag  could you ptal?

2023-02-08 08:18 UTC, mkumatag approved these changes
/lgtm

2023-02-08 08:18 UTC, mkumatag commented on cmd/capibmadm/cmd/powervs/network/list.go
> +	}
I see a scope for optimising the Printer function itself to handle this logic, definitely not part of this PR!

2023-02-08 08:21 UTC, merged