Add powervs network create and delete cmd
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1159
Opened 2023-03-14 17:39 UTC by yussufsh

**What this PR does / why we need it**:
Add support for following commands:

1. powervs network create
2. powervs network delete

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Add powervs network create and delete commands.
```

2023-03-14 17:40 UTC, Prajyot-Parab commented
/ok-to-test

2023-03-14 18:10 UTC, Prajyot-Parab requested changes

2023-03-14 18:10 UTC, Prajyot-Parab commented on docs/book/src/topics/capibmadm/powervs/network.md
>  IBMCLOUD_API_KEY: IBM Cloud api key.
nit: api -> API
same change at other places too.

2023-03-14 18:10 UTC, Prajyot-Parab commented on docs/book/src/topics/capibmadm/powervs/network.md
>  --service-instance-id: Power VS service instance id.
nit: Power VS -> PowerVS

2023-03-15 04:28 UTC, Prajyot-Parab commented
/cc @Karthik-K-N

2023-03-15 09:35 UTC, Karthik-K-N commented
/lgtm

2023-03-15 09:44 UTC, mkumatag approved these changes
I'm replying on the review by @Prajyot-Parab and @Karthik-K-N

2023-03-15 09:52 UTC, merged