Add Webhooks for IBMPowerVSClusterTemplate
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1174
Opened 2023-03-30 05:33 UTC by KeerthanaAP

**What this PR does / why we need it**:
Add Webhooks for IBMPowerVSClusterTemplate

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Fix https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/975

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2023-03-30 06:24 UTC, mkumatag commented
/cc @Prajyot-Parab 
/ok-to-test

2023-03-31 05:30 UTC, Prajyot-Parab requested changes
@KeerthanaAP As mentioned earlier we dont have webhooks in `v1beta1`, this should go in `v1beta2`.

2023-04-03 13:35 UTC, KeerthanaAP commented on api/v1beta1/ibmpowervsclustertemplate_webhook.go
> +/*
Done. Moved web hooks to v1beta2

2023-04-04 09:59 UTC, KeerthanaAP commented
> @KeerthanaAP As mentioned earlier we dont have webhooks in `v1beta1`, this should go in `v1beta2`.

@Prajyot-Parab These changes are done and ready for review.

2023-04-05 14:20 UTC, Prajyot-Parab approved these changes
/lgtm

2023-04-05 14:21 UTC, Prajyot-Parab commented
@KeerthanaAP please squash the commits into a single one.

2023-04-06 07:26 UTC, Prajyot-Parab approved these changes
/lgtm

2023-04-06 07:27 UTC, Prajyot-Parab commented
@KeerthanaAP just add release note in description.

2023-04-06 16:51 UTC, Prajyot-Parab approved these changes
/approve

2023-04-10 13:37 UTC, mkumatag approved these changes
/lgtm

2023-04-10 13:45 UTC, merged