Refactor cluster templates
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1341
Opened 2023-08-11 10:24 UTC by Amulyam24

**What this PR does / why we need it**:
This PR refactors the construction of cluster templates by reducing code duplication.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #855 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2023-08-11 17:51 UTC, Prajyot-Parab commented
@Amulyam24 
Is this the same behavior on your machine as well?

```
cluster-api-provider-ibmcloud % make generate-templates
./hack/version.sh: line 95: GIT_MAJOR: unbound variable
hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template.yaml
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs.yaml
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-cloud-provider --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-cloud-provider.yaml
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-clusterclass --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-clusterclass.yaml
hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-vpc-load-balancer --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-vpc-load-balancer.yaml
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

2023-08-12 07:29 UTC, Amulyam24 commented
> @Amulyam24 Is this the same behavior on your machine as well?
> 
> ```
> cluster-api-provider-ibmcloud % make generate-templates
> ./hack/version.sh: line 95: GIT_MAJOR: unbound variable
> hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template.yaml
> # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs.yaml
> # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-cloud-provider --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-cloud-provider.yaml
> # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-clusterclass --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-powervs-clusterclass.yaml
> hack/tools/bin/kustomize build /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-vpc-load-balancer --load-restrictor LoadRestrictionsNone > /Users/prajyotparab/Workspace/sandbox/cluster-api-provider-ibmcloud/templates/cluster-template-vpc-load-balancer.yaml
> # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> ```

yes @Prajyot-Parab. Made changes for the warning regarding deprecation of `patchesStrategicMerge` except for `cluster-template-vpc-load-balancer` since it has multiple patches in one, will see if that can be changed too.

2023-08-14 08:18 UTC, Prajyot-Parab commented
> @Amulyam24 Is this the same behavior on your machine as well?

> yes @Prajyot-Parab. Made changes for the warning regarding deprecation of `patchesStrategicMerge` except for `cluster-template-vpc-load-balancer` since it has multiple patches in one, will see if that can be changed too.

@Amulyam24 Checked looking good, let me know if its possible fix `vpc-load-blancer` template as well.

2023-08-14 12:28 UTC, Amulyam24 commented
> > @Amulyam24 Is this the same behavior on your machine as well?
> 
> > yes @Prajyot-Parab. Made changes for the warning regarding deprecation of `patchesStrategicMerge` except for `cluster-template-vpc-load-balancer` since it has multiple patches in one, will see if that can be changed too.
> 
> @Amulyam24 Checked looking good, let me know if its possible to fix `vpc-load-blancer` template as well.

@Prajyot-Parab, split the patches. PR is ready for review. PTAL

2023-08-14 12:33 UTC, Amulyam24 commented
/cc @mkumatag

2023-08-20 18:03 UTC, mkumatag approved these changes
/lgtm

2023-08-20 18:05 UTC, mkumatag requested changes

2023-08-20 18:05 UTC, mkumatag commented on Makefile
> +.PHONY: generate-templates
We should explore how consume this target! @Amulyam24 can you create a follow up task for that?

2023-08-20 18:05 UTC, mkumatag commented
lets merge this meanwhile

/approve

2023-08-20 18:19 UTC, merged

2023-08-22 09:04 UTC, Prajyot-Parab commented on templates/cluster-template-vpc-load-balancer.yaml
> +                secretName: ibm-cloud-credentia
`ibm-cloud-credentia -> ibm-cloud-credential`

@Amulyam24 typo error

2023-08-22 09:05 UTC, Prajyot-Parab commented on templates/addons/crs.yaml
> +                secretName: ibm-cloud-credentia
`ibm-cloud-credentia -> ibm-cloud-credential`

@Amulyam24 another one here