Add documentation for E2E testing
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1504
Opened 2023-11-19 07:00 UTC by Amulyam24

**What this PR does / why we need it**:
Add documentation for E2E testing

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1291 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Add documentation for E2E testing
```

2023-11-20 05:09 UTC, Amulyam24 commented
/cc @mkumatag

2023-11-20 14:55 UTC, mkumatag requested changes

2023-11-21 05:14 UTC, Amulyam24 commented on docs/book/src/SUMMARY.md
> +- [E2E testing](./e2e.md)
Addressed, PTAL.

2023-11-21 09:04 UTC, mkumatag approved these changes
/lgtm

2023-11-21 09:31 UTC, merged