Streamline documentation for CAPIBM
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1508
Opened 2023-11-21 14:26 UTC by kishen-v

**What this PR does / why we need it**: 
This PR removes redundant documentation. 

**Which issue(s) this PR fixes**:
Fixes #1507

**Special notes for your reviewer**: This PR can be co-authored to have more changes addressing other documentation issues. Please feel free to /hold if needed.

/area kind/documentation

**Release note**:

```release-note
NONE
```

2023-11-21 17:22 UTC, mkumatag requested changes

2023-11-23 05:29 UTC, mkumatag commented
/cc @Prajyot-Parab @Karthik-K-N 
please review

2023-11-23 05:29 UTC, mkumatag commented
/ok-to-test

2023-11-24 12:57 UTC, kishen-v commented on docs/book/src/developer/tilt.md
> +###  3. Create a kind cluster
Made changes in docs as suggested. Thanks!

2023-11-24 12:57 UTC, kishen-v commented on docs/book/src/developer/tilt.md
> +## Alternatively, tilt can be set up using Podman by following the steps below
Agree with your suggestion and have made the required changes.

2023-11-27 10:05 UTC, kishen-v commented
/cc @Amulyam24.

2023-11-27 13:31 UTC, Prajyot-Parab commented on docs/book/src/developer/tilt.md
> +If the user chooses to have Podman as the CRI, the follow the steps listed below:
```suggestion
If the user chooses to have Podman as the CRI, then follow the steps listed below:
```

2023-11-27 13:35 UTC, Prajyot-Parab commented on docs/book/src/developer/tilt.md
> +Restart Podman machine
```suggestion
### 3. Restart Podman machine
```

2023-11-27 13:40 UTC, Prajyot-Parab commented on docs/book/src/getting-started.md
>  ### Deploy with Cloud Contoller manager
```suggestion
### Deploy with Cloud Controller manager
```

2023-11-27 13:47 UTC, Prajyot-Parab commented on docs/book/src/getting-started.md
LINE 91

> 7. For deploying with your workload cluster with Cloud Controller manager or Cluster Class template, refer to [deploy with cloud controller manager](#deploy-with-cloud-controller-manager) and [deploy PowerVS cluster with cluster class template](#deploy-powervs-cluster-with-clusterclass-template) sections respectively.

2023-11-27 14:15 UTC, Amulyam24 commented on docs/book/src/getting-started.md
> -   1. To deploy VPC workload cluster with [IBM cloud controller manager](/topics/vpc/load-balancer.html), set the `PROVIDER_ID_FORMAT` environmental variable.
<img width="794" alt="Screenshot 2023-11-27 at 7 03 18 PM" src="https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/assets/30797554/0b83a696-7fc0-428d-8dab-114f61c9a87b"> 
From preview, please re-check the formatting.

2023-11-27 14:21 UTC, Amulyam24 commented on docs/book/src/developer/tilt.md
> +Currently, [ClusterResourceSet](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-resource-set.html) is an experimental feature. This requires setting the feature gate `EXP_CLUSTER_
I see that is is being repeated in two sections here, maybe we can mention this point as a note in the beginning to avoid redundancy?

2023-11-27 14:28 UTC, Amulyam24 commented on docs/book/src/developer/tilt.md
> +1. Emulate docker cli with Podman: Instructions can be found [here](https://podman-desktop.io/docs/migrating-from-docker/emulating-docker-cli-with-podman)
```suggestion
1. Emulate Docker CLI with Podman: Instructions can be found [here](https://podman-desktop.io/docs/migrating-from-docker/emulating-docker-cli-with-podman)
```

2023-11-28 05:14 UTC, mkumatag commented
@Amulyam24 @Karthik-K-N @Prajyot-Parab please review it and give an ack when its ready

2023-11-28 05:26 UTC, Karthik-K-N commented
/lgtm

2023-11-28 06:00 UTC, mkumatag approved these changes
/lgtm

2023-11-28 06:01 UTC, mkumatag commented
/hold

feel free to remove once other folks are comfortable

2023-11-28 06:05 UTC, Prajyot-Parab approved these changes
/lgtm

2023-11-28 06:09 UTC, Amulyam24 approved these changes
/lgtm

/unhold

2023-11-28 06:22 UTC, Karthik-K-N approved these changes

2023-11-28 06:34 UTC, merged