Replaced pvsadm image import reference with capibmadm powervs image import
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #1584
Opened 2024-01-17 10:08 UTC by irapandey

**What this PR does / why we need it**:
In this PR, reference of `pvsadm image import` are replaced with the new CLI command to import images - `powervs image import`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1583

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
 NO
 
**Release note**:

```release-note

```

2024-01-17 13:57 UTC, Prajyot-Parab commented
/easycla

2024-01-18 08:55 UTC, Prajyot-Parab commented
/easycla

2024-01-18 09:59 UTC, Prajyot-Parab commented
/cc @mkumatag

2024-01-18 12:11 UTC, Karthik-K-N reviewed
Lets make sure that command works as expected, Lets wait for @irapandey to update on that.
/hold

2024-01-22 06:44 UTC, Karthik-K-N reviewed
@irapandey since v0.7.0 is the latest release and which contains the image import command, could you please update this doc https://cluster-api-ibmcloud.sigs.k8s.io/topics/capibmadm/#install-capibmadm to use the same version as well.

2024-01-22 10:02 UTC, Karthik-K-N reviewed
```
$ capibmadm powervs image import --service-instance-id 3229a94c-af54-4212-bf60-6202b6fd0a07  --zone osa21 --bucket-region jp-tok --object RHEL9.0-image.ova.gz  --name test_image_new11 --public-bucket -b  keerthananewbucket
```
Importing PowerVS images:  service-instance-id="3229a94c-af54-4212-bf60-6202b6fd0a07"


Image Import Job in-progress, current state="running"
Image Import Job in-progress, current state="running"
Image Import Job in-progress, current state="running"
Retrieving image details
Successfully imported the image: test_image_new11 with ID: 77150236-44f6-4330-b7e1-4566a2512450 within 8m5.529332044s


Verified the image import command, Please update the PR with suggestions.

2024-01-22 10:02 UTC, Karthik-K-N commented on docs/book/src/topics/powervs/prerequisites.md
> +$ capibmadm powervs image import --service-instance-id c6c6945a-b6c6-4283-b0a9-14a702bdc764  --zone syd04 -r us-south --object rhcos-412.86.202208090152-0-powervs.ppc64le.ova.gz  --pvs-image-name tes
```suggestion
$ capibmadm powervs image import --service-instance-id 3229a94c-af54-4212-bf60-6202b6fd0a07  --zone osa21 --bucket-region jp-tok --object RHEL9.0-image.ova.gz  --name powervs_image --public-bucket -b  ocp-development-public-bucket
```

2024-01-25 04:47 UTC, irapandey commented
Just updated the PR - can you check @Karthik-K-N ?

2024-01-25 05:01 UTC, Karthik-K-N commented on docs/book/src/topics/powervs/prerequisites.md
> +$ capibmadm powervs image import --service-instance-id c6c6945a-b6c6-4283-b0a9-14a702bdc764  --zone syd04 -r us-south --object rhcos-412.86.202208090152-0-powervs.ppc64le.ova.gz  --pvs-image-name tes
@irapandey Please update this as well to use --bucket-region instead of -r and --powervs-image-name with -name as suggested above

2024-01-30 16:57 UTC, Prajyot-Parab requested changes

2024-01-30 16:57 UTC, Prajyot-Parab commented on docs/book/src/topics/powervs/prerequisites.md
> +$ capibmadm powervs image import --service-instance-id 3229a94c-af54-4212-bf60-6202b6fd0a07  --zone osa21 --bucket-region jp-tok --object RHEL9.0-image.ova.gz  --name powervs_image --public-bucket -b
```suggestion
$ capibmadm powervs image import --service-instance-id 3229a94c-af54-4212-bf60-6202b6fd0a07  --zone osa21 --bucket-region jp-tok --object RHEL9.0-image.ova.gz  --name powervs_image --public-bucket --bucket  ocp-development-public-bucket
```
Maintain parity between command format mentioned and example commad

2024-01-30 16:57 UTC, Prajyot-Parab commented on docs/book/src/topics/powervs/prerequisites.md
> +$ capibmadm powervs image import --service-instance-id <SERVICE_INSTANCE_ID>  --zone <ZONE> --bucket-region <BUCKET_REGION> --object <OBJECT>  --name <POWERVS_IMAGE_NAME> --bucket <BUCKETNAME> --publ
```suggestion
$ capibmadm powervs image import --service-instance-id <SERVICE_INSTANCE_ID>  --zone <ZONE> --bucket-region <BUCKET_REGION> --object <OBJECT>  --name <POWERVS_IMAGE_NAME> --bucket <BUCKETNAME> --public-bucket
```
Nit: trailing space

2024-02-07 05:09 UTC, Karthik-K-N approved these changes
/lgtm

2024-02-07 06:26 UTC, Karthik-K-N commented
@irapandey Could you please squash commits as well.

2024-02-07 06:46 UTC, Prajyot-Parab approved these changes
/lgtm

2024-02-07 14:25 UTC, mkumatag approved these changes
I will let @Karthik-K-N to remove the hold, thanks.

2024-02-07 14:49 UTC, Karthik-K-N commented
/hold cancel

2024-02-07 14:54 UTC, merged