Support bootstrap only additional listener
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #2059
Opened 2024-11-21 17:47 UTC by hamzy

Add an option to the AdditionalListenerSpec to signify that this pool should only contain the boostrap node.  An example of this would be for port 22 since every master node also has ssh but we need the public load balancer to only connect to the bootstrap ssh server and not randomly to any one of the four nodes.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2024-11-22 02:21 UTC, Karthik-K-N commented
/ok-to-test

2024-11-22 13:07 UTC, Karthik-K-N commented
Overall I like the idea just thinking, Can we generalise this rather than sticking only to bootstrap configuration?
Say tomorrow we want to configure something only on the master nodes then we need to make the changes again.
I would like to know the opinions
@dharaneeshvrd @Amulyam24 @Prajyot-Parab

2024-11-25 05:17 UTC, dharaneeshvrd commented
> Overall I like the idea just thinking, Can we generalise this rather than sticking only to bootstrap configuration?
Say tomorrow we want to configure something only on the master nodes then we need to make the changes again.

+1

2024-12-16 19:16 UTC, hamzy commented
@Karthik-K-N @dharaneeshvrd 
What do you think now?

2024-12-17 11:31 UTC, Karthik-K-N reviewed
This approach looks good to me in general but would like to know @dharaneesh openion as well.

2024-12-17 11:31 UTC, Karthik-K-N commented on cloud/scope/powervs_machine.go
> +					shouldAdd = strings.Contains(m.IBMPowerVSMachine.Name, "-master")
I am not sure need to check but I think rather than name we can use labels/anotations which identify that a machine is control-plan or data?

2024-12-17 11:33 UTC, Karthik-K-N commented
Tagging @cjschaef as he might thought about it or might have some other approach.

2024-12-17 17:08 UTC, hamzy commented
> Tagging @cjschaef as he might thought about it or might have some other approach.

Are we bike shedding?

2025-01-02 12:30 UTC, hamzy commented
Can we progress on this?  It's been two weeks and this is an important issue.

2025-01-03 06:41 UTC, dharaneeshvrd commented on api/v1beta2/ibmvpccluster_types.go
> +	// AdditionalListenerAll add every VM to the listener pool.
Using 0, 1 & 2 to identify the nodes does not look good to me. Can we define the possible values using enum like [this](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/api/v1beta2/types.go#L138) and add the necessary kubebuilder validation?

2025-01-03 06:41 UTC, dharaneeshvrd commented on cloud/scope/powervs_machine.go
> +					shouldAdd = strings.Contains(m.IBMPowerVSMachine.Name, "-master")
I too feel using static strings to identify the nodes is not a good idea. If there is no other way we can go with this approach.

2025-01-03 07:40 UTC, mkumatag requested changes

2025-01-03 07:40 UTC, mkumatag commented on api/v1beta2/ibmvpccluster_types.go
> +	AdditionalListenerBootstrapOnly
there is nothing like bootstrap term in the capi project, we need to find some generic way to deal with this problem.

2025-01-03 07:50 UTC, mkumatag requested changes
doesn't matter, can we have something like - add the machines based on the condition set in the `AdditionalListenerSpec` spec e.g: some label/annotation so that we can make this generic.

e.g:

```
selectors:
      - "powervs.cluster.x-k8s.io/node-type": "bootstrap"
```

and bootstrap machine can have this annotation to get added into that additional listener.

default: we can keep the current behaviour as is to add all the machines if no selector specified.
>The bootstrap VM is not technically a node.

2025-01-03 14:55 UTC, hamzy commented
Do you have a code example for querying a selector in Go?

2025-01-04 04:46 UTC, mkumatag commented
> Do you have a code example for querying a selector in Go?

I don't have code handy

2025-01-07 04:22 UTC, dharaneeshvrd commented on cloud/scope/powervs_machine.go
> +				default:
Don't we need to set `shouldAdd = true` here also, when it's not set? Also can you please add UT covering this new logic?

2025-01-07 06:30 UTC, Karthik-K-N commented on cloud/scope/powervs_machine.go
> +				machineType, ok := m.IBMPowerVSMachine.ObjectMeta.Labels["powervs.cluster.x-k8s.io/node-type"]
Should we use  label or annotation for selecting the machines to configure, Usually CAPI uses annotation to select the machines.
https://github.com/Karthik-K-N/cluster-api/blob/f3d39741b47ae458625a28e6b37e3adeb18dfeb1/api/v1beta1/common_types.go#L98-L103

2025-01-07 06:31 UTC, Karthik-K-N commented on cloud/scope/powervs_machine.go
> +				default:
Yes, The default case workflow should be like the existing behavior, It should not break the existing flow.

2025-01-07 06:32 UTC, Karthik-K-N commented on api/v1beta2/ibmvpccluster_types.go
> +	Add VPCLoadBalancerPoolAdd `json:"add,omitempty"`
Can we rename it with better name, Something like MachineSelector or something?

2025-01-07 13:57 UTC, hamzy commented on cloud/scope/powervs_machine.go
> +				default:
The default case throws an error so it does not need shouldAdd to be set.
What is UT?  Do you have an example of how to implement it?

2025-01-07 15:53 UTC, mkumatag commented on cloud/scope/powervs_machine.go
> +				default:
first lets focus on finalising the API spec, see my comments in the api/

2025-01-07 15:56 UTC, closed without merging