Adding unit tests- powervs
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #339
Opened 2021-09-08 10:37 UTC by Amulyam24

**What this PR does / why we need it**:
This PR adds unit tests for PowerVS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan @mkumatag 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

2021-09-08 10:43 UTC, mkumatag commented
/ok-to-test

2021-09-13 04:38 UTC, mkumatag commented
cc @Karthik-K-N

2021-09-13 05:39 UTC, Amulyam24 commented
I signed it

2021-09-13 06:00 UTC, Karthik-K-N commented
/lgtm

2021-09-13 06:36 UTC, mkumatag requested changes
lgtm for the initial commit, need to explore the options for mocking the client and cover more scenarios,

some minor nits

2021-09-13 06:36 UTC, mkumatag commented on controllers/ibmpowervscluster_controller_test.go
> +	AfterEach(func() {})
do we need these if empty?

2021-09-13 06:36 UTC, mkumatag commented on controllers/ibmpowervsmachine_controller_test.go
> +	AfterEach(func() {})
same as above

2021-09-13 07:23 UTC, Amulyam24 commented on controllers/ibmpowervscluster_controller_test.go
> +	AfterEach(func() {})
No, we can skip them.

2021-09-13 07:39 UTC, mkumatag requested changes

2021-09-13 07:39 UTC, mkumatag commented on controllers/ibmpowervscluster_controller_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client"
minor import formatting

```suggestion
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/klog/v2/klogr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	
	"github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/api/v1alpha4"
	
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
```

2021-09-13 07:39 UTC, mkumatag commented on controllers/ibmpowervsmachine_controller_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client"
same suggestion as above

2021-09-13 07:48 UTC, Amulyam24 commented on controllers/ibmpowervscluster_controller_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client"
Updated @mkumatag

2021-09-13 08:05 UTC, mkumatag commented
/retest

2021-09-13 08:43 UTC, mkumatag approved these changes
/lgtm

2021-09-13 08:45 UTC, merged