Support JUnit XML test report
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #340
Opened 2021-09-17 09:10 UTC by Amulyam24

**What this PR does / why we need it**:
This PR provides the ability to generate JUnit XML test reports and populate the prow dashboard accordingly for the unit tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #328 

**Specify your PR reviewers**:

/cc @gyliu513 @jichenjc @xunpan @mkumatag 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

2021-09-17 09:12 UTC, Amulyam24 commented
cc @Rajalakshmi-Girish

2021-09-17 09:18 UTC, mkumatag commented
/ok-to-test

2021-09-17 09:23 UTC, mkumatag commented
> @Amulyam24: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-cluster-api-provider-ibmcloud-test	[ee1889e](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commit/ee1889e9a65fd48f26d793680593220fc550ffe3)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/340/pull-cluster-api-provider-ibmcloud-test/1438794493162688512)	`/test pull-cluster-api-provider-ibmcloud-test`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api-provider-ibmcloud&pr=340). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3AAmulyam24). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues?q=is:issue+is:open) when you hit one in your PR.

seems like this failure is happening here as well @Amulyam24 @Rajalakshmi-Girish

2021-09-17 09:42 UTC, mkumatag commented
/retest

2021-09-17 09:48 UTC, Rajalakshmi-Girish commented
> 
> 
> > @Amulyam24: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name	Commit	Details	Rerun command
> > pull-cluster-api-provider-ibmcloud-test	[ee1889e](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commit/ee1889e9a65fd48f26d793680593220fc550ffe3)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/340/pull-cluster-api-provider-ibmcloud-test/1438794493162688512)	`/test pull-cluster-api-provider-ibmcloud-test`
> > [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api-provider-ibmcloud&pr=340). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3AAmulyam24). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> seems like this failure is happening here as well @Amulyam24 @Rajalakshmi-Girish

@Amulyam24 This failure seems to occur when make lint takes more than 1minute to execute.
You may try including --timeout option at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/Makefile#L116

2021-09-17 09:51 UTC, Rajalakshmi-Girish commented
The default value is 1m as mentioned here https://golangci-lint.run/usage/configuration/#command-line-options

2021-09-17 09:57 UTC, Amulyam24 commented
After the initial test failure with timeout, the retest fails with `/bin/sh: 1: go-junit-report: not found`
I'll make the changes to add a higher timeout as well to avoid the issue.

2021-09-17 09:59 UTC, Amulyam24 commented
> > > @Amulyam24: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > > Test name	Commit	Details	Rerun command
> > > pull-cluster-api-provider-ibmcloud-test	[ee1889e](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commit/ee1889e9a65fd48f26d793680593220fc550ffe3)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/340/pull-cluster-api-provider-ibmcloud-test/1438794493162688512)	`/test pull-cluster-api-provider-ibmcloud-test`
> > > [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api-provider-ibmcloud&pr=340). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3AAmulyam24). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues?q=is:issue+is:open) when you hit one in your PR.
> > 
> > 
> > seems like this failure is happening here as well @Amulyam24 @Rajalakshmi-Girish
> 
> @Amulyam24 This failure seems to occur when make lint takes more than 1minute to execute.
> You may try including --timeout option at https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/Makefile#L116

Thanks @Rajalakshmi-Girish , will update it.

2021-09-17 10:11 UTC, mkumatag commented
> After the initial test failure with timeout, the retests fails with `/bin/sh: 1: go-junit-report: not found`
> I'll make the changes to add a higher timeout as well to avoid the issue.

this may be because you just vendored but not really installed it. just see if you can install it like [here](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/a5766245b5a6f5380d719380983933522649e469/Makefile#L119)

2021-09-17 11:04 UTC, Amulyam24 commented
@mkumatag, made the required changes, PTAL.

2021-09-17 11:07 UTC, mkumatag requested changes
looking at the test results, it just shows only one entry, not sure why?!

2021-09-17 11:07 UTC, mkumatag commented on Makefile
> +REPORT_NAME := $(JUNIT_REPORT_NAME)
no default set if not passed

2021-09-17 11:07 UTC, mkumatag commented on Makefile
> +	go test ./... -v 2>&1 | $(GO_JUNIT_REPORT) > $(REPORT_NAME).xml
I'm wondering if we can make optional, generate xml only when mentioned(especially via CI scripts)

2021-09-17 11:18 UTC, mkumatag commented
@Amulyam24 see if this helps for the ginkgo - https://onsi.github.io/ginkgo/#generating-junit-xml-output

2021-09-17 12:44 UTC, Amulyam24 commented
> looking at the test results, it just shows only one entry, not sure why?!

Yes, go-junit-report is only considering the test suite as a whole and not the individual test cases unlike using the ginkgo package. I'll look more on it.

> I'm wondering if we can make optional, generate xml only when mentioned(especially via CI scripts)

@mkumatag, are you mentioning about making it optional via the `scripts/ci-test.sh` or through prow yaml. I'll have to explore the possibility of making it optional with the current flow, since with prow, the presence of artifacts will always lead to generation of the XML reports.

2021-09-17 13:15 UTC, mkumatag commented
> @mkumatag, are you mentioning about making it optional via the `scripts/ci-test.sh` or through prow yaml. I'll have to explore the possibility of making it optional with the current PR flow, since with prow, the presence of artifacts will always lead to generation of the XML reports.

not with prow, e.g: if someone triggers these tests manually then it shouldn't generate the xml and generate the xml only if the option mentioned like some env like GENERATE_JUNIT, some of the logic can be derived from the kubernetes/kubernetes repo(something can be worked as followup PR).

2021-09-20 12:09 UTC, Amulyam24 commented
@mkumatag, updated with changes. PTAL.

2021-09-20 13:36 UTC, mkumatag approved these changes
/lgtm
/approve

2021-09-20 13:38 UTC, merged