Add webhook for IBMPowerVS resources
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #488
Opened 2021-12-14 15:41 UTC by Prajyot-Parab

Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
1. Add Webhooks with default and validation logic for IBMPowerVS* resources.
2. **TODO** - Add Webhooks with default and validation logic for IBMVPC* resources.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #434 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2021-12-14 16:35 UTC, mkumatag commented
/ok-to-test

2021-12-14 17:02 UTC, mkumatag requested changes

2021-12-15 10:26 UTC, Prajyot-Parab commented on api/v1beta1/ibmpowervsmachine_webhook.go
> +}
The content is slightly different from one another so I think we can stick to the present version of code.

2021-12-15 10:27 UTC, Prajyot-Parab commented on main.go
> +	}
<TODO> - have faced issues with vpc webhook changes while registering, will implement in next set of changes.

2021-12-15 10:32 UTC, Prajyot-Parab commented on api/v1beta1/ibmpowervscluster_webhook.go
> +}
I tried moving it to a common location and use interface to switch between different source types that didn't work, will circle back on this one while implementing vpc related changes.

2021-12-15 11:09 UTC, mkumatag requested changes

2021-12-15 11:09 UTC, mkumatag commented on api/v1beta1/ibmpowervsmachine_webhook.go
> +}
see if this helps:
```suggestion
// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *IBMPowerVSMachine) Default() {
	ibmpowervsmachinelog.Info("default", "name", r.Name)
	defaultIBMPowerVSMachineSpec(&r.Spec)
}

func defaultIBMPowerVSMachineSpec(spec *IBMPowerVSMachineSpec) {
	if spec.Memory == "" {
		spec.Memory = "8"
	}
	if spec.Processors == "" {
		spec.Processors = "0.25"
	}
	if spec.SysType == "" {
		spec.SysType = "s922"
	}
	if spec.ProcType == "" {
		spec.ProcType = "shared"
	}
}
```

2021-12-15 11:18 UTC, mkumatag commented on main.go
> +	}
it will be great if you can create an issue for the same.

2021-12-16 06:00 UTC, mkumatag approved these changes
/lgtm

2021-12-16 06:01 UTC, merged