Fix network/image webhook validations
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #523
Opened 2022-01-25 08:32 UTC by Prajyot-Parab

Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Fix network name and id related webhook validation checks
- Fix image name and id related webhook validation checks

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #521 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2022-01-25 10:07 UTC, Prajyot-Parab commented
> Instead of this, I'm wondering if we can have following marker for the API spec to force user to specify the non empty string like:
> 
> ```
> +kubebuilder:validation:MinLength=1
> ```

checking

2022-01-25 14:45 UTC, mkumatag requested changes

2022-01-25 14:45 UTC, mkumatag commented on api/v1beta1/ibmpowervsmachine_types.go
> +	// +kubebuilder:validation:MinLength=1
can we set this `+kubebuilder:validation:MinLength=1` for the `ServiceInstanceID` as well?

2022-01-25 14:45 UTC, mkumatag commented
/ok-to-test

2022-01-31 06:35 UTC, mkumatag requested changes
fix the test failure as well.

2022-01-31 06:35 UTC, mkumatag commented on api/v1alpha4/ibmpowervscluster_types.go
> +	// +kubebuilder:validation:MinLength=1
lets not change change anything in the older version, will focus only on v1beta1 and onwards,

2022-01-31 08:50 UTC, mkumatag approved these changes
/lgtm
/approve

2022-01-31 08:54 UTC, merged