Refactor VPC client code
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #668
Opened 2022-05-09 12:10 UTC by Amulyam24

**What this PR does / why we need it**:
This PR moves the VPC client code to `pkg/cloud/services` for better mocking in unit tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #532 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

2022-05-09 12:33 UTC, mkumatag commented
@Prajyot-Parab ptal

2022-05-10 05:32 UTC, Prajyot-Parab approved these changes
/lgtm

2022-05-10 14:18 UTC, mkumatag requested changes

2022-05-10 14:18 UTC, mkumatag commented on pkg/cloud/services/vpc/vpc.go
> +// Vpc interface defines methods that a Cluster API IBMCLOUD object should implement.
@Amulyam24 do you mind adding generator for the mock as well here?

2022-05-11 10:57 UTC, mkumatag approved these changes
/lgtm
/approve

2022-05-11 10:59 UTC, merged