Improve UT coverage in cloud/scope package for PowerVS
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #741
Opened 2022-07-06 19:10 UTC by Prajyot-Parab

Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Improve UT coverage in cloud/scope package for PowerVS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Improve UT coverage in cloud/scope package for PowerVS
```

2022-07-06 19:10 UTC, Prajyot-Parab commented
/cc @mkumatag @Amulyam24

2022-07-07 12:00 UTC, mkumatag requested changes

2022-07-07 18:50 UTC, Prajyot-Parab commented on cloud/scope/powervs_image_test.go
> +	. "github.com/onsi/gomega"
Fixed.

2022-07-07 18:51 UTC, Prajyot-Parab commented on cloud/scope/powervs_machine_test.go
> +	"sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/cloud/services/powervs/mock"
Fixed.

2022-07-08 05:28 UTC, mkumatag approved these changes
/lgtm

2022-07-08 05:29 UTC, merged