Fix mock PowerVS client calls in unit tests
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #761
Opened 2022-07-18 11:02 UTC by Amulyam24

**What this PR does / why we need it**:
- Refactors the UT structure 
- Fixes mock PowerVS client calls

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2022-07-18 11:26 UTC, Amulyam24 commented
/cc @Prajyot-Parab @mkumatag

2022-07-19 07:17 UTC, mkumatag requested changes

2022-07-19 07:17 UTC, mkumatag commented on cloud/scope/cluster_test.go
> +			defer teardown()
Use `t.Cleanup()` instead of defer(applies to all the occurrences.

2022-07-20 06:50 UTC, Prajyot-Parab approved these changes
/lgtm

2022-07-20 06:58 UTC, merged