Add doc for dependecy version mapping
kubernetes-sigs/cluster-api-provider-ibmcloud pull request #961
Opened 2022-11-15 06:48 UTC by Amulyam24

**What this PR does / why we need it**:
Adds information about the versions being used by a few important modules and tools.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #930 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2022-11-15 06:52 UTC, Amulyam24 commented
/cc @mkumatag 

Please let me know if the K8s bits and IBM Cloud module dependencies should also be added.

2022-11-15 07:02 UTC, mkumatag requested changes

2022-11-15 07:02 UTC, mkumatag commented on docs/book/src/reference/version-dependencies.md
> +# Versions dependency mapping
This doc is meant for the developer for keeping the project up to dated with the possible latest versions.

2022-11-15 07:02 UTC, mkumatag commented on docs/book/src/reference/version-dependencies.md
> +| cluster-api | [sigs.k8s.io/cluster-api](https://github.com/kubernetes-sigs/cluster-apis) | v1.2.5 |
It will also be good if we can mention what go dep file we are targeting here? one in the root dir and tools

2022-11-15 07:02 UTC, mkumatag commented on docs/book/src/reference/version-dependencies.md
> +| IBM Cloud CLI | v2.12.0 | [ibm-cloud-cli-release](https://github.com/IBM-Cloud/ibm-cloud-cli-release.git) |
again in which script?

2022-11-15 09:15 UTC, Amulyam24 commented
Addressed the comments, PTAL.

2022-11-18 12:06 UTC, mkumatag approved these changes
/lgtm

2022-11-18 12:14 UTC, merged